# services:
#   webapplication1:
#     image: ${DOCKER_REGISTRY-}webapplication1
#     build:
#       context: .
#       dockerfile: WebApplication1/Dockerfile

# For å komme inn i databasen fra terminalen: 

# docker exec -it mariadb mariadb -u root -p

version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Deadpool77
      MYSQL_DATABASE: webapplication
      MYSQL_USER: root
      MYSQL_PASSWORD: Deadpool77
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=webapplication;User=root;Password=Deadpool77;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: